services:
  api:
    build:
      context: ./api
    restart: always
    env_file:
      - ./api/.env
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
  postgres:
    build:
      context: ./db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data # this is where the database data will be stored
    ports:
      - "${DB_PORT}:${DB_PORT}"
  db-backups:
    build:
      context: ./db-backups
    volumes:
      - ./db-backups/backups:/backups # this is where the backups will be stored locally
      - ./db-backups/rclone.conf:/root/.config/rclone/rclone.conf # rclone config file for Google Drive
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    entrypoint: ["sh", "-c", "while true; do /backup.sh --prod; sleep 86400; done"]

volumes:
  pgdata: